python -u run.py \
  --task_name long_term_forecast \
  --project_name dualformer \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model dualformer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 24 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  
python -u run.py \
  --task_name long_term_forecast \
  --project_name dualformer \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_192 \
  --model dualformer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 24 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  
python -u run.py \
  --task_name long_term_forecast \
  --project_name dualformer \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_336 \
  --model dualformer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 24 \
  --pred_len 336 \
  --e_layers 3 \
  --d_layers 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  
python -u run.py \
  --task_name long_term_forecast \
  --project_name dualformer \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_720 \
  --model dualformer \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 24 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 